### ISSUE TITLE
[bilibili.tv] subtitle can't generate

### ISSUE THREAD

**Issue by cjrayance** [AdvMaple/biliintl_subtitle_download_plugin#28]
I think it should only happen with new episodes from spring 2023 onwards. 

can you try on : [https://www.bilibili.tv/th/play/2073192/12704020?bstar_from=bstar-web.pgc-video-detail.episode.all](url)

or : [https://www.bilibili.tv/th/play/2075126/12691563?bstar_from=bstar-web.pgc-video-detail.episode.all](url) The first episode will still be able to generate subtitles, will not be able to generate from episode 6 onwards.

**Comment by AdvMaple** [comment]
I'll look into this asap

**Comment by AdvMaple** [comment]
I've just looked into this, this is because Bilibili now returns .ass file directly! Hooray! 🎉 🎉 Beautiful subtitle for everyone.
Some of the old subtitles still use json subtitles <-- boo! json doesn't support typesetting.
I'll develop a fix right away for this 🤗 new feature  
Well, bad news for this is the file type converter is now has to be temporary disable :cry:

**Comment by AdvMaple** [comment]
Resolved with df240f54c7fbb31e222621040ba9446c88929df0 :rocket: 
Thank you for reporting this problem.  
Feel free to re-open if this happen again.

**Comment by cjrayance** [comment]
I tested it and it works, thank you very much sir
